SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

-- Insert 10 sample promotions into the PROMOTION table
INSERT INTO PROMOTION (TITLE) VALUES ('Spring Sale');
INSERT INTO PROMOTION (TITLE) VALUES ('Summer Clearance');
INSERT INTO PROMOTION (TITLE) VALUES ('Black Friday Deal');
INSERT INTO PROMOTION (TITLE) VALUES ('Holiday Special');
INSERT INTO PROMOTION (TITLE) VALUES ('New Year Offer');
INSERT INTO PROMOTION (TITLE) VALUES ('Back to School');
INSERT INTO PROMOTION (TITLE) VALUES ('Flash Discount');
INSERT INTO PROMOTION (TITLE) VALUES ('Member Exclusive');
INSERT INTO PROMOTION (TITLE) VALUES ('Limited Time Offer');
INSERT INTO PROMOTION (TITLE) VALUES ('Buy One Get One');

COMMIT;

EXIT
