<html lang="en">
<head>
    <title>Login</title>
</head>
<body>
<h1>Login</h1>
<form method="post">
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required>
    <br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password" required>
    <br>
    <button type="submit">Login</button>
</form>
<p>Don't have an account? <a href="/myapp-0.1-dev/register">Register here</a></p>
</body>
</html>
